config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'forecast', to: 'forecast#index', as: 'forecast'
  root "forecast#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/forecast_controller.rb
# frozen_string_literal: true

class ForecastController < ApplicationController
  def index
    @address = address_params || 'Tampa, FL'
    weather_data = ForecastService.new(@address).get_weather_data

    if weather_data.present?
      set_weather_data(weather_data)
      @from_cache = cached_weather_data?(@address)
    else
      flash[:alert] = 'Unable to fetch weather data for the given address.'
      render :index
    end
  end

  private

  def address_params
    params[:address]
  end

  def set_weather_data(weather_data)
    @current_temperature = weather_data['main']['temp']
    @high_temperature = weather_data['main']['temp_max']
    @low_temperature = weather_data['main']['temp_min']
  end

  def cached_weather_data?(address)
    Rails.cache.exist?("weather_data_#{address}")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forecast_helper.rb
# frozen_string_literal: true

module ForecastHelper
end

app/views/forecast/index.html.erb
<h1>Weather Forecast</h1>

<%= form_tag(forecast_path, method: :get) do %>
  <div class="form-group">
    <%= label_tag :address, 'Enter an address:' %>
    <%= text_field_tag :address, @address, class: 'form-control' %>
  </div>
  <%= submit_tag 'Get Weather', class: 'btn btn-primary' %>
<% end %>

<% if @current_temperature.present? %>
  <div class="weather-info">
    <h3>Current Temperature: <%= @current_temperature %> °C</h3>
    <h4>High Temperature: <%= @high_temperature %> °C</h4>
    <h4>Low Temperature: <%= @low_temperature %> °C</h4>
    <% if @from_cache %>
      <p class="text-muted">Data from cache</p>
    <% else %>
      <p class="text-muted">Data fetched from API</p>
    <% end %>
  </div>
<% end %>

<% if flash[:alert].present? %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>